### ISSUE TITLE
Translations cause problems when running rebuild

### ISSUE THREAD

**Issue by pc-coholic** [pc-coholic/pretix-cashpayment#1]
In production, the german Umlauts seems to cause problems when running `python -m pretix rebuild`.

Probably need to properly mark up the .po-files as UTF-8 or something like that.

**Comment by tiefpunkt** [comment]
Ran into this problem yesterday, managed to fix it, see #2.

**Comment by pc-coholic** [comment]
Thank you so much for this :)

I wanted to fix that but kinda forgot about it down the road ;-)
